### ISSUE TITLE
ICDrama Not working?

### ISSUE THREAD

**Issue by casperooi** [cthlo/plugin.video.icdrama#2] opened 2016-10-17 13:05 UTC
Hi support,

Just tested the ICDrama addon on KODI today but found that all Chinese dramas, movies etc not working.. Is there some URL issue?

**Comment by Matheaw** [comment] 2016-10-17 17:09
@casperooi @cthlo Having the same issue here. Is the website make some changes on their URL again? Just tested their website, is working. 
http://icdrama.se/

**Comment by cthlo** [comment] 2016-10-17 18:42
Yes, it seems like there is some change to the site. Looking at it now. Thanks!

**Comment by cthlo** [comment] 2016-10-17 22:59
I've applied fixes. Please verify. Thanks.

**Comment by Siuluuu** [comment] 2016-10-17 23:16
Just tried one episode and it is working. Many Thanks!

**Comment by cthlo** [comment] 2016-10-17 23:38
Thanks. I'll close this issue in a couple days.

(Fix applied to version 1.2.3)

**Comment by Matheaw** [comment] 2016-10-18 01:32
Thanks, is working fine now. I'm curios if this addon can use the official rss feed from icdrama. As it will always pull the latest sources from the icdrama. Then maybe it will be easier to maintain.
http://irss.se/dramas/beta.html

**Comment by casperooi** [comment] 2016-10-18 02:09
Hi cthlo, how about the add-on for icdrama & azdrama under cthlo-kodi-repo? Will the fix applied as well? Once again, thanks for the great and prompt support.

**Comment by cthlo** [comment] 2016-10-18 06:24
@Matheaw Huh, I did not know there was a feed with all the streams. I might switch to that later on.

@casperooi Yes, the fixed version is in the repo.

Thank you guys for reporting.

**Comment by poemex** [comment] 2016-10-18 10:28
hi @cthlo mine device not working, means once i go in choose channel then kodi keep say working

**Comment by casperooi** [comment] 2016-10-18 11:07
@cthlo, the icdrama fixed but azdrama.net still the same issue. 1.1.5

**Comment by poemex** [comment] 2016-10-18 11:12
ICdrama @casperooi mine not work it keep saying working but no video out, could you help?

**Comment by casperooi** [comment] 2016-10-18 11:22
@poemex, are you able to check the ICDrama add on version? it should be 1.2.3. Mine one so far no issue.

**Comment by poemex** [comment] 2016-10-18 11:28
Mine is 1.2.3

**Comment by penanghunter** [comment] 2016-10-18 14:15
Hi cthlo,
Newer version of the urlresolver will try to update then icdrama will not run.. need to goto SYSTEM -> Setting -> Add-ons -> System -> Dependencies -> goto the lowest URLResolver, click it then disable the Auto-update.. while there double check the version you should be using is 3.0.1 and not 3.0.22. If already updated, then just click Update and install back the 3.0.1... then icdrama will run fine..
But since the newer 3.0.22 is used by Exodus, by forcing it now back to 3.0.1 not sure what will happen to Exodus.

**Comment by dodgy3000** [comment] 2016-10-18 14:32
penanghunter, your solution works, thank you. Seems the problem is the URLResolver. Downgrading to 3.0.1 solved the problem for now.

**Comment by dodgy3000** [comment] 2016-10-18 15:06
penanghunter, your solution works for 30 minutes. after that, it's the same problem again, it doesnt work anymore even if i use 3.01 or 3.0.22.

**Comment by casperooi** [comment] 2016-10-18 15:17
I have tested the urlresolver until version 3.21, it is working, just 3.22 will not work.

**Comment by dodgy3000** [comment] 2016-10-18 15:26
casperooi, i can't find 3.21 option there. 3.01 and 3.22 doesn't seem to work now.

**Comment by casperooi** [comment] 2016-10-18 16:07
@dodgy3000, lets use the 3.01 at the moment, while waiting @cthlo to apply fix on 3.22 and Azdrama.net add on

**Comment by cthlo** [comment] 2016-10-18 17:50
Thanks for reporting! Fix is uploaded (v1.2.4)

I'm no longer maintaining the azdrama addon. If you are interested in using that, you should be able find the latest from the author's repo.

**Comment by tweety1668** [comment] 2016-10-18 18:13
after update icdrama to latest version, it worked this morning, but now stuck on working spinning

**Comment by cthlo** [comment] 2016-10-18 18:21
@tweety1668 Please check for an update, again. v1.2.4 should fix the problem

**Comment by dodgy3000** [comment] 2016-10-19 00:43
Tested v1.2.4 too. It's not working. It's stuck when "Allupload:Full" is clicked, error message is URL not found. Tried it with URLResolver v3.01 and v.3.22. Same result, it doesn't work. Thanks for your help cthlo.

**Comment by cthlo** [comment] 2016-10-19 00:47
Which episode/movie are you trying access?

**Comment by poemex** [comment] 2016-10-19 01:19
thanx @cthlo Ic drama is working now !!!!!

**Comment by dodgy3000** [comment] 2016-10-19 12:25
@cthlo HK movies Line Walker and HK drama The Hiddens all episode. Actually all HK dramas and HK movies not working. The error message when I click on the episodes is URL not found.

**Comment by casperooi** [comment] 2016-10-19 13:35
@dodgy3000 pls try to update the repository.cthlo.kodi-repo-1.0.0.zip

**Comment by cthlo** [comment] 2016-10-21 04:45
1.2.3, 1.2.4

**Closed as completed by cthlo** 2016-10-21 04:45 UTC

**Comment by jethoven** [comment] 2017-03-30 11:11
Thanks @cthlo   ! are you not maintaining azdrama anymore and going forward using icdrama?

**Comment by cthlo** [comment] 2017-03-30 23:18
I was only temporarily patching azdrama when the owner of the addon was gone. I'm not actually maintaining that addon.
